// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OkayEnough {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Blob {
    #[prost(bytes="vec", tag="1")]
    pub datum: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobList {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<Blob>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TopicSize {
    #[prost(int32, tag="1")]
    pub length: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownstreamList {
    #[prost(uint32, tag="1")]
    pub jitter_seconds: u32,
    #[prost(uint32, tag="2")]
    pub delay_seconds: u32,
    #[prost(string, repeated, tag="3")]
    pub target_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Target {
    #[prost(string, tag="1")]
    pub target_uri: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub status: u32,
    #[prost(string, tag="3")]
    pub msg: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownstreamStatus {
    #[prost(uint32, tag="1")]
    pub jitter_seconds: u32,
    #[prost(uint32, tag="2")]
    pub delay_seconds: u32,
    #[prost(bool, tag="3")]
    pub is_forwarding: bool,
    #[prost(string, optional, tag="4")]
    pub last_run_completion: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub targets: ::prost::alloc::vec::Vec<Target>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetForwarding {
    #[prost(bool, tag="1")]
    pub is_forwarding: bool,
}
// @@protoc_insertion_point(module)
