// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OkayEnough {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Blob {
    #[prost(bytes = "vec", tag = "1")]
    pub datum: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlobList {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<Blob>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TopicSize {
    #[prost(int32, tag = "1")]
    pub length: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownstreamList {
    #[prost(uint32, tag = "1")]
    pub jitter_seconds: u32,
    #[prost(uint32, tag = "2")]
    pub delay_seconds: u32,
    #[prost(string, repeated, tag = "3")]
    pub targets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
